<?php
return ['x-generator'=>'GlotPress/4.0.1','translation-revision-date'=>'2020-05-19 15:53:19+0000','plural-forms'=>'nplurals=2; plural=n != 1;','project-id-version'=>'Plugins - Error Log Monitor - Stable (latest release)','language'=>'es','messages'=>['Recommended: To log all types of errors instead of only fatal errors and warnings, also find the line %1$s and change it to %2$s.'=>'Recomendado: para registrar todo tipo de errores en lugar de solo los errores fatales y advertencias, busca la línea %1$s y cámbiala a %2$s.','Checking configuration...'=>'Comprobando la configuración...','Setup complete!'=>'¡Configuración completada!','Please follow the manual configuration instructions instead.'=>'Por favor, en su lugar, sigue las instrucciones de configuración manual.','a link to Pro version informationDetails'=>'Detalles','Documentation: %s'=>'Documentación: %s','setup wizard buttonDone'=>'Hecho','setup wizard error prefixThere was an error:'=>'Ha habido un error:','Manual Configuration Instructions'=>'Instrucciones de configuración manual','To get started you need to do two things:'=>'Para comenzar, debes hacer dos cosas:','Create a log file.'=>'Crear un archivo de registro.','Configure PHP to write all errors to that file.'=>'Configura PHP para escribir todos los errores en ese archivo.','Creating a Log File'=>'Crear un archivo de registro','Change the file permissions to allow PHP to write to the file. This step will vary depending on 
				the server configuration. If you\'re unsure what permissions to use, try using the same settings as
				for the files in %s, or refer to the documentation provided by your hosting provider.'=>'Cambia los permisos del archivo para permitir que PHP escriba en él. Este paso variará dependiendo de 
				la configuración del servidor. Si no estás seguro de qué permisos usar, intenta usar los mismos ajustes de
				los archivos en %s o consulta la documentación proporcionada por tu proveedor de alojamiento.','Next, please add this code to %1$s and replace the placeholder %2$s with the actual path to the new log file:'=>'A continuación, por favor, añade este código a %1$s y reemplaza el marcador de posición %2$s con la ruta actual al nuevo archivo de registro:','More information about WP_DEBUG.'=>'Más información acerca de `WP_DEBUG`','When that\'s done, please go to the Dashboard. You should see a message like 
			"Log is empty" in the "PHP Error Log" widget. This is normal - the log will stay empty 
			until an error actually happens.'=>'Cuando termine, por favor, ve al escritorio. Deberías ver un mensaje como: 
			«El registro está vacío» en el widget «Registro de errores de PHP». Esto es normal - el registro permanecerá vacío 
			hasta que realmente ocurra un error.','Could not find a suitable location for the log file.'=>'No se ha podido encontrar una ubicación adecuada para el archivo de registro.','Also, find the line %1$s and change it to %2$s. This code enables "debug" mode in WordPress. 
				This is makes it possible to log everything including PHP notices and other minor errors. 
				If debugging is disabled, WordPress will automatically change error reporting settings to log 
				only fatal errors and warnings.'=>'También, busca la línea %1$s y cámbiala a %2$s. Este código activa el modo de «depuración» en WordPress. 
				Esto permite registrar todo, incluyendo los avisos de PHP y otros errores menores. 
				Si la depuración está desactivada, WordPress cambiará automáticamente los ajustes del informe de errores para registrar
				solo errores fatales y advertencias.','Could not create a log file in directory <code>%s</code>.'=>'No se ha podido crear un archivo de registro en el directorio <code>%s</code>.','The log file already exists but it is not writable: <code>%s</code>.'=>'El archivo de registro ya existe, pero no tiene permisos de escritura: <code>%s</code>.','Error Log Monitor setup'=>'Configuración de Error Log Monitor','setup wizard buttonHide Manual Instructions'=>'Ocultar las instrucciones manuales','First, decide where you want to put the log file on your server. 
			For security purposes, it should usually be in a directory that can\'t be accessed by site visitors 
			and non-admin users. For example, you could create a "php-logs" directory above the web root and 
			place the file there.'=>'Primero, decide dónde deseas colocar el archivo de registro en tu servidor.
			Por razones de seguridad, generalmente debe estar en un directorio al que no puedan acceder los visitantes del sitio 
			y usuarios no administradores. Por ejemplo, puedes crear un directorio «php-logs» encima del directorio raíz de la web y
			colocar el archivo allí.','Create an empty text file and upload it to your selected directory. The file name doesn\'t matter. 
				Here are some suggestions: %s'=>'Crea un archivo de texto vacío y súbelo en el directorio seleccionado. El nombre del archivo no importa. 
				Aquí hay algunas sugerencias: %s','Changing the PHP Configuration'=>'Cambiando la configuración de PHP','The log file will be empty at first. This is normal. When any PHP errors happen, they should show up in the log.'=>'El archivo de registro estará vacío al principio. Esto es normal. Cuando se producen errores de PHP, deben aparecer en el registro.','To start logging errors you\'ll need to make a few changes to the WordPress configuration.'=>'Para comenzar a registrar errores, debes realizar algunos cambios en la configuración de WordPress.','Use Recommended Settings'=>'Usar los ajustes recomendados','setup wizard buttonManual Configuration'=>'Configuración manual','Creating a log file...'=>'Creando un archivo de registro...','Please add this code to your %s and then click "Done":'=>'Por favor, añade este código a tu %s y luego haz clic en «Hecho»:','Freemius account linkAccount'=>'Cuenta','How often to check the log for new messages:'=>'Frecuencia de comprobación del log para mensajes nuevos:','Every 5 minutes'=>'Cada 5 minutos','Every 2 minutes'=>'Cada 2 minutos','Upgrade to Pro'=>'Actualizar a Pro','the heading of the upgrade-to-pro section in widget settingsPro Version'=>'Versión Pro','By default, only fatal errors and warnings will be logged. To also log notices
                and other messages, enable the <code>WP_DEBUG</code> option by adding this code:'=>'Por defecto, sólo errores fatales y advertencias serán incluidos. Para incluir también avisos y otros mensajes, activa la opción <code>WP_DEBUG</code> agregando este código:','show hidden stack trace itemsShow %d more'=>'Mostrar %d más','a link that hides the "Upgrade to Pro" noticeHide'=>'Ocultar','View Pricing'=>'Ver precios','Upgrade to Pro for more detailed logs and a summary view.'=>'Actualizar a pro para logs más detallados y una vista resumen.','Sorry, you are not allowed to change these settings.'=>'Lo siento, no tienes permiso para cambiar estos ajustes.','Stack Trace'=>'Seguimiento de la pila','tooltip for the email fieldYou can enter multiple emails by separating them with a comma.'=>'Puedes incluir varios correos electrónicos seprándolos con coma.','Widget layout:'=>'Diseño del widget:','Ignored messages stay in the log file but they don\'t show up in the widget and don\'t generate email notifications.'=>'Los mensajes ignorados permanecen en el archivo de registro, pero no se muestran en el widget y no generan avisos por correo electrónico.','action linkIgnore'=>'Ignorar','configuration section headingGeneral'=>'General','widget layout optionTable'=>'Tabla','widget layout optionList'=>'Lista','configuration section headingNotifications'=>'Avisos','configuration section headingFilters'=>'Filtros','Dashboard widget filter'=>'Filtro del widget del escritorio','Email notification filter'=>'Filtro de avisos por correo electrónico','Ignored messages'=>'Mensajes ignorados','There are no ignored messages.'=>'No hay mensajes ignorados.','action linkUnignore'=>'Dejar de ignorar','Notify only about selected types'=>'Avisar solo sobre los tipos seleccionados','There are no recent log entries that match the filter settings.'=>'No hay entradas de registro recientes que coincidan con los ajustes del filtro.','Show all messages'=>'Mostrar todos los mensajes','Show only selected types'=>'Solo mostrar los tipos seleccionados','Same as the dashboard widget'=>'Igual que el widget del escritorio','error typeOther'=>'Otro','%d entry was filtered out.'=>'%d entrada ha sido filtrada.' . "\0" . '%d entradas han sido filtradas.','Send an email notification when the log file size exceeds this limit:'=>'Enviar un aviso por correo electrónico cuando el tamaño del archivo de registro supere este límite:','PHP error log file size has exceeded %1$s on %2$s'=>'El tamaño del archivo de registro de errores de PHP ha superado %1$s en %2$s','For reference, the full path of the WordPress directory is:<br>%s'=>'Para referencia, la ruta completa del directorio de WordPress es: <br>%s','Site URL: %1$s
Log file: %2$s
Size: %3$s
'=>'URL del sitio: %1$s
Archivo de registro: %2$s
Tamaño: %3$s

','PHP Error Log'=>'Registro de errores de PHP','Clear Log'=>'Vaciar el registro','Are you sure you want to clear the error log?'=>'¿Seguro que quieres vaciar este registro?','Strip WordPress root directory from log messages'=>'Quitar el directorio raíz de WordPress de los mensajes de registro','Reverse line order (most recent on top)'=>'Orden inverso de líneas (la más reciente en la parte superior)','How often to send email (max):'=>'Con qué frecuencia enviar el correo electrónico (máximo):','Log cleared.'=>'Registro vaciado.','The current error_log value <code>%s</code> is not supported. Please change it to an absolute path.'=>'El valor actual de `error_log` <code>%s</code> no es compatible. Por favor, cámbialo a una ruta absoluta.','The log file <code>%s</code> exists, but is not accessible. Please check file permissions.'=>'El archivo de registro <code>%s</code> existe, pero no es accesible. Por favor, revisa los permisos del archivo.','Could not open the log file "%s".'=>'No se ha podido abrir el archivo de registro «%s».','http://w-shadow.com/'=>'http://w-shadow.com/','Janis Elsts'=>'Janis Elsts','Adds a Dashboard widget that displays the last X lines from your PHP error log, and can also send you email notifications about newly logged errors.'=>'Añade un widget de escritorio que muestra las últimas X líneas del registro de errores de PHP y también puede enviarte avisos por correo electrónico acerca de los errores recién registrados.','http://w-shadow.com/blog/2012/07/25/error-log-monitor-plugin/'=>'http://w-shadow.com/blog/2012/07/25/error-log-monitor-plugin/','Error Log Monitor'=>'Error Log Monitor','Log file: %1$s (%2$s)'=>'Archivo de registro: %1$s (%2$s)','The log file is empty.'=>'El archivo de registro está vacío.','To enable error logging, create an empty file named "php-errors.log".
			Place it in a directory that is not publicly accessible (preferably outside
			your web root) and ensure it is writable by the web server.
			Then add the following code to <code>wp-config.php</code>:'=>'Para activar el registro de errores, crea un archivo vacío llamado «php-errors.log».
			Colócalo en un directorio que no sea de acceso público (preferiblemente fuera 
de la raíz de tu web) y asegúrate de que el servidor web tenga permisos de escritura.
			Luego, añade el siguiente código a <code>wp-config.php</code>:','See also: %s'=>'Ver también: %s','Number of entries to show:'=>'Número de entradas a mostrar:','Periodically email logged errors to:'=>'Envíar correos electrónicos de forma periódica con los errores registrados a:','Every 10 minutes'=>'Cada 10 minutos','Every 15 minutes'=>'Cada 15 minutos','Every 30 minutes'=>'Cada 30 minutos','Hourly'=>'Cada hora','Daily'=>'Diario','Weekly'=>'Semanal','Error logging is disabled.'=>'El registro de errores está desactivado.','Error log filename is not set.'=>'El archivo de registro de errores no está configurado.','The log file <code>%s</code> does not exist or is inaccessible.'=>'El archivo de registro <code>%s</code> no existe o es inaccesible.','PHP errors logged on %s'=>'Errores de PHP registrados en %s','New PHP errors have been logged on %1$s
Here are the last %2$d entries from %3$s:

'=>'Se han registrado nuevos errores de PHP en %1$s
Estos son los últimos %2$d registros desde %3$s:

','Settings <strong>saved</strong>.'=>'Ajustes <strong>guardados</strong>.','Settings'=>'Ajustes']];