<?php
return ['x-generator'=>'GlotPress/4.0.1','translation-revision-date'=>'2021-02-22 13:16:24+0000','plural-forms'=>'nplurals=1; plural=0;','project-id-version'=>'Plugins - Error Log Monitor - Stable (latest release)','language'=>'ko_KR','messages'=>['button titleClear Ignored Messages'=>'무시한 안내문 지우기','progress text when clearing ignored messagesProcessing...'=>'처리 중...','action link: mark an error as not fixedUnmark'=>'표시 해제하기','No messages have been marked as fixed.'=>'수정한 것으로 표시한 안내문이 없어요.','table headingMarked as fixed'=>'수정한 것으로 표시했어요','action linkMark as fixed'=>'수정한 것으로 표시하기','Mark the error as fixed and hide it. If this error happens again in the future, it will become visible again.'=>'오류를 수정한 것으로 표시하고 숨겨요. 이 오류가 다시 일어나면, 다시 보이게 되요.','Also, find the line %1$s and change it to %2$s. This code enables "debug" mode in WordPress. 
				This is makes it possible to log everything including PHP notices and other minor errors. 
				If debugging is disabled, WordPress will automatically change error reporting settings to log 
				only fatal errors and warnings.'=>'또한, %1$s행을 찾아 %2$s(으)로 바꿔요. 이 코드는 워드프레스에서 “디버그” 모드를 활성화해요. 
				PHP 안내와 다른 소소한 오류를 포함하는 모든 것을 기록하도록 해요. 
				활성해제되었으면, 워드프레스는 자동으로 오류 보고 설정을 치명적인 오류와 경고만 
				기록하도록 바꾸게 될 거에요.','Change the file permissions to allow PHP to write to the file. This step will vary depending on 
				the server configuration. If you\'re unsure what permissions to use, try using the same settings as
				for the files in %s, or refer to the documentation provided by your hosting provider.'=>'파일 권한을 PHP가 파일을 기록할 수 있게 변경해요. 이 단계는 서버 구성에 따라 
				달라져요. 사용하는 권한이 무엇인지 확실하지 않으면, %s에 있는 파일과 같이
				사용하거나, 호스팅 업체가 제공하는 문서를 참조하여 시도해요.','Changing the PHP Configuration'=>'PHP 구성 바꾸는 중','Checking configuration...'=>'구성 확인 중...','Configure PHP to write all errors to that file.'=>'그 파일에 모든 오류를 기록하도록 PHP를 구성해요.','Could not create a log file in directory <code>%s</code>.'=>'<code>%s</code> 디렉토리에 기록 파일을 만들 수 없어요.','Could not find a suitable location for the log file.'=>'기록 파일에 대한 알맞는 위치를 찾을 수 없어요.','Create a log file.'=>'기록 파일을 만들어요.','Create an empty text file and upload it to your selected directory. The file name doesn\'t matter. 
				Here are some suggestions: %s'=>'빈 문서 파일을 만들고 선택한 디렉토리에 올려요. 파일 이름은 상관 없어요. 
				여기 몇 가지를 제안해요: %s','Creating a Log File'=>'기록 파일을 만드는 중','Creating a log file...'=>'기록 파일 만드는 중...','Documentation: %s'=>'문서: %s','Error Log Monitor setup'=>'오류 기록 감시기 설정','First, decide where you want to put the log file on your server. 
			For security purposes, it should usually be in a directory that can\'t be accessed by site visitors 
			and non-admin users. For example, you could create a "php-logs" directory above the web root and 
			place the file there.'=>'먼저, 기록 파일을 서버 어디에 두기를 원하는 지 결정해요. 
			보안 목적으로, 보통 사이트 방문자와 관리자 아닌 사용자가 접근할 수 없는 
			디렉토리여야 해요. 예를 들면, 웹루트 위에 “php-logs” 디렉토리를 만들고 
			그 파일을 거기 둬요.','Manual Configuration Instructions'=>'직접 구성 지침','More information about WP_DEBUG.'=>'WP_DEBUG에 대한 더 자세한 정보에요.','Next, please add this code to %1$s and replace the placeholder %2$s with the actual path to the new log file:'=>'다음으로, 이 코드를 %1$s에 넣고 자리표시자 %2$s(을)를 새 기록 파일의 실제 경로로 바꿔요:','Please add this code to your %s and then click "Done":'=>'%s에 이 코드를 넣고 “완료”를 누르시기 바래요:','Please follow the manual configuration instructions instead.'=>'대신 직접 구성 지침을 따르시기 바래요.','Recommended: To log all types of errors instead of only fatal errors and warnings, also find the line %1$s and change it to %2$s.'=>'추천: 치명적인 오류와 경고를 기록하는 대신 모든 유형의 오류를 기록하려면, %1$s행을 찾고 %2$s(으)로 변경하세요.','Setup complete!'=>'설정을 완료했어요!','The log file already exists but it is not writable: <code>%s</code>.'=>'기록 파일이 이미 있지만 기록할 수 없어요: <code>%s</code>.','The log file will be empty at first. This is normal. When any PHP errors happen, they should show up in the log.'=>'기록 파일은 처음에는 비어 있어요. 이게 일반적이에요. 어떤 PHP 오류가 생기면, 기록에 보이게 될 거에요.','To get started you need to do two things:'=>'시작하려면 2가지를 해야해요:','To start logging errors you\'ll need to make a few changes to the WordPress configuration.'=>'오류 기록을 시작하면 워드프레스 구성에서 몇 가지를 변경할 필요가 있어요.','Use Recommended Settings'=>'추천 설정 사용','When that\'s done, please go to the Dashboard. You should see a message like 
			"Log is empty" in the "PHP Error Log" widget. This is normal - the log will stay empty 
			until an error actually happens.'=>'다 했으면, 알림판으로 가요. “PHP 오류 기록” 위젯에 “기록이 비었어요”와 같은 
			안내문을 보게 되요. 이게 일반적이고 실제로 오류가 생길 때까지 오류는 
			비어있을 거에요.','setup wizard buttonDone'=>'완료','setup wizard buttonHide Manual Instructions'=>'직접 지침 숨기기','setup wizard buttonManual Configuration'=>'직접 구성','setup wizard error prefixThere was an error:'=>'오류가 있어요:','a link to Pro version informationDetails'=>'자세히','By default, only fatal errors and warnings will be logged. To also log notices
                and other messages, enable the <code>WP_DEBUG</code> option by adding this code:'=>'기본적으로, 치명적인 오류와 경고만 기록될 거에요. 또한 안내와 
                다른 안내문을 기록하려면, 다음의 코드를 넣어 <code>WP_DEBUG</code> 선택지를 활성화하세요:','Every 2 minutes'=>'매 2분','Every 5 minutes'=>'매 5분','Freemius account linkAccount'=>'계정','How often to check the log for new messages:'=>'얼마나 자주 새 안내문에 대한 기록을 확인하나요:','Sorry, you are not allowed to change these settings.'=>'죄송해요, 이 설정을 바꾸도로 허용되지 않았네요.','Stack Trace'=>'스택 추적','Upgrade to Pro'=>'프로로 승격하기','Upgrade to Pro for more detailed logs and a summary view.'=>'더 자세한 기록과 요약 보기를 위해 프로로 승격하세요.','View Pricing'=>'가격 보기','a link that hides the "Upgrade to Pro" noticeHide'=>'Hide','show hidden stack trace itemsShow %d more'=>'%d개 더 보기','the heading of the upgrade-to-pro section in widget settingsPro Version'=>'프로판','tooltip for the email fieldYou can enter multiple emails by separating them with a comma.'=>'쉼표로 구분하여 여러 이메일을 입력할 수 있어요.','Dashboard widget filter'=>'알림판 위젯 거르미','Email notification filter'=>'이메일 알림 거르미','Ignored messages'=>'무시된 안내문','Ignored messages stay in the log file but they don\'t show up in the widget and don\'t generate email notifications.'=>'무시된 안내문이 기록 파일에 있으나 위젯에서 보이지 않고 이메일 알림을 만들지 않아요.','There are no ignored messages.'=>'무시된 안내문이 없어요.','Widget layout:'=>'위젯 배치:','action linkIgnore'=>'무시','action linkUnignore'=>'무시해제','configuration section headingFilters'=>'거르미','configuration section headingGeneral'=>'일반','configuration section headingNotifications'=>'알림','widget layout optionList'=>'목록','widget layout optionTable'=>'표','%d entry was filtered out.'=>'%d개의 항목이 걸려졌어요.','Notify only about selected types'=>'선택된 유형에 대해서만 알리기','Same as the dashboard widget'=>'알림판 위젯과 같게','Show all messages'=>'모든 안내문 보이기','Show only selected types'=>'선택된 유형만 보이기','There are no recent log entries that match the filter settings.'=>'거름 설정과 일치하는 최신 기록 항목이 없어요.','error typeOther'=>'기타','For reference, the full path of the WordPress directory is:<br>%s'=>'참고로 워드프레스 디렉토리의 전체 경로는:<br>%s','PHP error log file size has exceeded %1$s on %2$s'=>'%2$s에 있는 %1$s(이)가 PHP 오류 기록 파일 크기를 넘겼어요','Send an email notification when the log file size exceeds this limit:'=>'기록 파일 크기가 다음의 제한을 넘기면 이메일 알림을 보내요:','Site URL: %1$s
Log file: %2$s
Size: %3$s
'=>'사이트 URL: %1$s
기록 파일: %2$s
크기: %3$s
','PHP Error Log'=>'PHP 오류 기록','Adds a Dashboard widget that displays the last X lines from your PHP error log, and can also send you email notifications about newly logged errors.'=>'PHP 오류 기록의 최근 X행을 보여주는 알림판 위젯이 추가하고, 새로 기록된 오류에 대한 이메일 알림을 보낼 수도 있어요.','Are you sure you want to clear the error log?'=>'오류 기록을 정리하기 원하시는게 확실한가요?','Clear Log'=>'기록 지우기','Could not open the log file "%s".'=>'기록 파일 “%s”(을)를 열 수 없어요.','Daily'=>'매 일','Error Log Monitor'=>'오류 기록 감시자','Error log filename is not set.'=>'오류 기록 파일이름을 설정하지 않았어요.','Error logging is disabled.'=>'오류 기록을 활성해제했어요.','Every 10 minutes'=>'매 10분','Every 15 minutes'=>'매 15분','Every 30 minutes'=>'매 30분','Hourly'=>'매 시간','How often to send email (max):'=>'얼마나 자주 이메일을 보내나요 (최대):','Janis Elsts'=>'제니스 엘스츠','Log cleared.'=>'기록이 정리되었어요.','Log file: %1$s (%2$s)'=>'기록 파일: %1$s (%2$s)','New PHP errors have been logged on %1$s
Here are the last %2$d entries from %3$s:

'=>'새 PHP 오류가 %1$s에 기록되었어요
여기에 %3$s의 %2$d개의 항목이 있어요:

','Number of entries to show:'=>'보여줄 항목의 수:','PHP errors logged on %s'=>'PHP 오류가 %s에 기록되었어요','Periodically email logged errors to:'=>'다음으로 기록된 오류를 정기적으로 이메일:','Reverse line order (most recent on top)'=>'줄 순서 뒤집기 (가장 최근이 위쪽)','See also: %s'=>'이것도 보세요: %s','Settings'=>'설정','Settings <strong>saved</strong>.'=>'설정이 <strong>저장되었어요</strong>.','Strip WordPress root directory from log messages'=>'기록 안내문에서 워드프레스 루트 디렉토리 벗기기','The current error_log value <code>%s</code> is not supported. Please change it to an absolute path.'=>'현재의 error_log 값인 <code>%s</code>(을)를 지원하지 않아요. 절대 경로를 변경하시기 바래요.','The log file <code>%s</code> does not exist or is inaccessible.'=>'기록 파일 <code>%s</code>(이)가 존재하지 않거나 접근할 수 없어요.','The log file <code>%s</code> exists, but is not accessible. Please check file permissions.'=>'기록 파일 <code>%s</code>(이)가 있지만, 접근할 수 없어요. 파일 권한을 확인하시기 바래요.','The log file is empty.'=>'기록 파일이 비었어요.','To enable error logging, create an empty file named "php-errors.log".
			Place it in a directory that is not publicly accessible (preferably outside
			your web root) and ensure it is writable by the web server.
			Then add the following code to <code>wp-config.php</code>:'=>'오류 기록을 활성화하면, “php-errors.log”라는 이름의 빈 파일이 만들어져요.
			공개 접근이 안 되는 디렉토리에 놓으시고(웹 루트 바깥이요)
			웹 서버에 의해 기록될 수 있는지 확인하세요.
			그런 다음 <code>wp-config.php</code>에 다음의 코드를 넣으세요:','Weekly'=>'매 주','http://w-shadow.com/'=>'http://w-shadow.com/','http://w-shadow.com/blog/2012/07/25/error-log-monitor-plugin/'=>'http://w-shadow.com/blog/2012/07/25/error-log-monitor-plugin/']];